### ISSUE TITLE
Run-time error - no location information for UIModalPresentationPopover

### ISSUE THREAD

**Issue by Spokane-Dude** [ryanmaxwell/UIAlertController-Blocks#3]
Put this code in my iPad app (XCode 6.1, iOS 8.1.1, Ojbective-c) to replace existing deprecated UIActionSheet and got this run-time error:
` *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x7fdfe3324f00>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'`
This is my code:
`    
    [UIAlertController showActionSheetInViewController:self
            withTitle:@"Test Action Sheet"
            message:NSLocalizedString(@"Are you sure you want to delete ALL appointments?",nil)
            cancelButtonTitle:@"Cancel"
             destructiveButtonTitle:@"Yes"
             otherButtonTitles:@[@"No"]  //  same as Cancel
             tapBlock:^(UIAlertController *controller, UIAlertAction *action, NSInteger buttonIndex){
                   if (buttonIndex == UIAlertControllerBlocksCancelButtonIndex) {
                        NSLog(@"Cancel Tapped");
                   } else if (buttonIndex == UIAlertControllerBlocksDestructiveButtonIndex) {
                        NSLog(@"Delete Tapped");
                   } else if (buttonIndex >= UIAlertControllerBlocksFirstOtherButtonIndex) {
                        NSLog(@"Other Action Index %ld", 
                               (long)buttonIndex - UIAlertControllerBlocksFirstOtherButtonIndex);
                    }
             }];`

None of your examples show anything that would correct this issue.  Can you advise how to correct this?

**Comment by ryanmaxwell** [comment]
resolved in https://github.com/ryanmaxwell/UIAlertController-Blocks/releases/tag/0.8
