### ISSUE TITLE
I will crash showAlertController on viewController is another presentViewController

### ISSUE THREAD

**Issue by tentenlee100** [ryanmaxwell/UIAlertController-Blocks#7]
in metthod 
`+ (instancetype)showInViewController:(UIViewController *)viewController
                           withTitle:(NSString *)title
                             message:(NSString *)message
                      preferredStyle:(UIAlertControllerStyle)preferredStyle
                   cancelButtonTitle:(NSString *)cancelButtonTitle
              destructiveButtonTitle:(NSString *)destructiveButtonTitle
                   otherButtonTitles:(NSArray *)otherButtonTitles
  popoverPresentationControllerBlock:(void(^)(UIPopoverPresentationController *popover))popoverPresentationControllerBlock
                            tapBlock:(UIAlertControllerCompletionBlock)tapBlock
{`

I'm add this code it will worked

`    UIWindow *alertWindow = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];`
`    UIViewController *vc = [[UIViewController alloc] init];`
`    alertWindow.rootViewController = vc;`
`    [alertWindow makeKeyAndVisible];`
`    [alertWindow.rootViewController presentViewController:controller animated:YES completion:nil];`

**Comment by ryanmaxwell** [comment]
Fixed in 0.9.2 thanks
